[package]
name = "ultimate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = ["tracing-appender", "opentelemetry"]
tonic = ["dep:tonic", "dep:prost"]
opentelemetry = [
  "dep:init-tracing-opentelemetry",
  "dep:tracing-opentelemetry-instrumentation-sdk",
]

[dependencies]
ultimate-common.workspace = true
thiserror.workspace = true
regex.workspace = true
futures.workspace = true
tokio.workspace = true
async-trait.workspace = true
toml.workspace = true
config.workspace = true
strum.workspace = true
uuid = { workspace = true }
ulid = { workspace = true }
log.workspace = true
tracing.workspace = true
# tracing-log.workspace = true
tracing-subscriber.workspace = true
tracing-appender = { workspace = true, optional = true }
init-tracing-opentelemetry = { workspace = true, optional = true }
tracing-opentelemetry-instrumentation-sdk = { workspace = true, optional = true }
rand.workspace = true
argon2.workspace = true
josekit.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
serde_repr.workspace = true
# utoipa = { workspace = true, optional = true }
tonic = { workspace = true, optional = true }
prost = { workspace = true, optional = true }

[dev-dependencies]
dotenvy.workspace = true
anyhow.workspace = true

[build-dependencies]
prost-build = { workspace = true }
