[package]
name = "ultimate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
publish = true

[lints]
workspace = true

[features]
with-db = ["dep:ultimate-db", "dep:modelsql"]
with-grpc = ["dep:ultimate-grpc", "dep:tonic"]
with-web = ["dep:ultimate-web", "dep:axum"]

[dependencies]
tokio = { workspace = true }
ultimate-core = { workspace = true }
# -- db & modelsql
ultimate-db = { workspace = true, optional = true }
modelsql = { workspace = true, optional = true }
# -- web & axum
ultimate-web = { workspace = true, optional = true }
axum = { workspace = true, optional = true }
# -- grpc & tonic
ultimate-grpc = { workspace = true, optional = true }
tonic = { workspace = true, optional = true }
