[package]
name = "ultimate-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
publish = true

[lints]
workspace = true

[features]
# default = ["with-uuid"]
tonic = ["dep:tonic", "ultimate-core/tonic"]
with-uuid = ["dep:uuid", "ultimate-core/with-uuid"]
with-ulid = ["dep:ulid", "ultimate-core/with-ulid"]

[dependencies]
ultimate-common.workspace = true
ultimate-core.workspace = true
futures.workspace = true
tokio.workspace = true
log.workspace = true
bytes.workspace = true
config.workspace = true
mime.workspace = true
hyper.workspace = true
tower.workspace = true
tower-http.workspace = true
http.workspace = true
headers.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
ulid = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }
# utoipa = { workspace = true, optional = true }
tonic = { workspace = true, optional = true }
