[ultimate.app]
run_mode = "DEV"
name = "guixu"

[ultimate.security.pwd]
expires_in = 604800
default_pwd = "2025.Guixu"

[ultimate.web]
enable = true
server_addr = "0.0.0.0:51000"

[ultimate.log]
enable = true
log_writer = "both"
with_span_events = []
log_targets = [
  "guixu=debug",
  "ultimate_db=debug",
  "ultimate_common=debug",
  "ultimate_core=debug",
  "ultimate_web=debug",
  "modelsql=debug",
]

[ultimate.db]
enable = true
host = "localhost"
port = 45432
database = "guixu"
username = "guixu"
password = "2025.Guixu"
schema_search_path = "guixu"

[ultimate.log.otel]
enable = false
exporter_otlp_endpoint = "http://localhost:4317"
traces_sample = "always_on"
