[package]
name = "fusiondata-context"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
ultimate-common = { workspace = true }
ultimate = { workspace = true }
ultimate-db = { workspace = true }
ultimate-grpc = { workspace = true }
fusiondata = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
