[ultimate.app]
run_mode = "DEV"
name = "fusion-metadata"

[ultimate.security.pwd]
expires_in = 604800
default_pwd = "2024.Fusiondata"

[ultimate.web]
enable = true
server_addr = "0.0.0.0:58020"

[ultimate.grpc]
enable = true
server_addr = "0.0.0.0:58030"
plaintext = true

[ultimate.db]
enable = true
host = "localhost"
port = 45432
database = "fusiondata"
username = "fusiondata"
password = "2024.Fusiondata"

[ultimate.log]
log_targets = [
  "fusion_scheduler=debug",
  "fusiondata=debug",
  "fusiondata_context=debug",
  "ultimate_grpc=debug",
  "ultimate_db=debug",
  "ultimate=debug",
  "ultimate_common=debug",
  "tower_http=debug",
]

[fusion-scheduler]
node_id = "node-1"
heartbeat_interval = "10s"
namespaces = ["default"]
