[ultimate.app]
run_mode = "DEV"
name = "hetumind"


# 添加队列配置
[hetumind.queue]
type = "postgres"
max_pool_size = 10
visibility_timeout = "30s"

# 添加工作流引擎配置
[hetumind.workflow.engine]
max_concurrent_executions = 10
node_timeout_seconds = 30
workflow_timeout_seconds = 300
memory_limit_mb = 1024

# 工作流全局配置
[hetumind.workflow]
error_handling_strategy = "StopOnFirstError"
execution_mode = 1                           # Local 单机执行模式
execution_timeout_ms = 7200000               # 2小时


[hetumind.workflow.engine.retry_config]
max_retries = 3
retry_interval_seconds = 10

[ultimate.security.pwd]
expires_in = 604800
default_pwd = "2025.Hetumind"

[ultimate.web]
enable = true
server_addr = "0.0.0.0:50000"

[ultimate.log]
enable = true
log_writer = "both"
with_span_events = []
log_level = "info"
log_targets = [
  "hetumind=debug",
  "hetumind_context=debug",
  "hetumind_nodes=debug",
  "hetumind_core=debug",
  "modelsql=debug",
  "modelsql_core=debug",
  "ultimate_db=debug",
  "ultimate_common=debug",
  "ultimate_core=debug",
  "ultimate_web=debug",
]

[ultimate.db]
enable = true
url = "postgresql://fusiondata:2025.Fusiondata@localhost:5432/fusiondata"

[ultimate.log.otel]
enable = false
exporter_otlp_endpoint = "http://localhost:4317"
traces_sample = "always_on"
