[fusion.app]
run_mode = "DEV"
name = "hetumind"

# 添加队列配置
[hetumind.queue]
type = "postgres"
max_pool_size = 10
visibility_timeout = "30s"

# 工作流全局配置
[hetumind.workflow]
error_handling_strategy = "StopOnFirstError"
execution_mode = 1                           # Local 单机执行模式
execution_timeout_ms = 7200000               # 2小时

# 添加工作流引擎配置
[hetumind.workflow.engine]
max_concurrent_executions = 10
node_timeout_seconds = 30
workflow_timeout_seconds = 300
memory_limit_mb = 1024

[hetumind.workflow.engine.retry_config]
max_retries = 3
retry_interval_seconds = 10
base_delay_ms = 1000
max_delay_ms = 60000
backoff_multiplier = 2.0
retryable_errors = ["timeout", "network", "resource_unavailable"]

[hetumind.workflow.engine.resource_management]
cpu_core_based_scaling = true
deadlock_detection_enabled = true
resource_allocation_strategy = "Adaptive"

[hetumind.binary_storage]
kind = "memory"
root = "/tmp"
max_pool_size = 10

[fusion.security.pwd]
expires_in = 604800
default_pwd = "2025.Hetumind"

[fusion.web]
enable = true
server_addr = "0.0.0.0:50000"

[fusion.log]
enable = true
log_writers = ["stdout", "file"]
with_span_events = []
log_level = "info"
log_targets = [
  "hetumind=debug",
  "hetumind_context=debug",
  "hetumind_nodes=debug",
  "hetumind_core=debug",
  "fusionsql=debug",
  "fusionsql_core=debug",
  "fusion_db=debug",
  "fusion_common=debug",
  "fusion_core=debug",
  "fusion_web=debug",
]

[fusion.db]
enable = true
url = "postgresql://fusiondata:2025.Fusiondata@localhost:5432/fusiondata"

[fusion.log.otel]
enable = false
exporter_otlp_endpoint = "http://localhost:4317"
traces_sample = "always_on"
