[ultimate.app]
run_mode = "dev"
name = "hetuflow-agent"
time_offset = "+08:00"

[ultimate.log]
enable = true
log_level = "info"
# ... 其他日志配置

# Agent 专属配置
[hetuflow.agent]
# Agent 的唯一标识符，若为空则自动生成
agent_id = "agent-node-01"
# Agent 标签，用于 Server 进行任务匹配
tags = ["linux", "x86_64", "gpu-enabled"]
# Agent 上报给 Server 的元数据
metadata = { region = "cn-hangzhou", owner = "data-team" }

# WebSocket 连接配置
[hetuflow.agent.websocket]
server_url = "ws://127.0.0.1:9500/ws/v1/connect"
reconnect_interval = "5s"
heartbeat_interval = "30s"
# 连接和握手超时时间
connect_timeout = "10s"

# 本地调度器配置
[hetuflow.agent.scheduler]
# Agent 实例上允许同时运行的最大任务数
max_concurrent_tasks = 20
# 时钟精度，时间轮的 tick duration
timer_precision = "50ms"

# 任务执行器配置
[hetuflow.agent.executor]
# 任务默认超时时间
default_task_timeout = "1h"
