[hetu.app]
run_mode = "DEV"
name = "hetu-iam"

[hetu.security.pwd]
expires_in = 604800
default_pwd = "2025.Ultimate"

[hetu.web]
enable = true
server_addr = "0.0.0.0:58000"

[hetu.log]
enable = true
log_writers = ["stdout", "file"]
with_span_events = []
log_targets = [
  "hetu_db=debug",
  "hetu_common=debug",
  "hetu_web=debug",
  "jieyuan=debug",
]

[hetu.log.otel]
# enable = true
exporter_otlp_endpoint = "http://localhost:4317"
traces_sample = "always_on"

[hetu.db]
enable = true
url = "postgres://fusiondata:2025.Fusiondata@localhost:5432/fusiondata"

[jieyuan.auth_provider.wechat]
client_id = ""
client_secret = ""
authorize_url = ""
redirect_uri = ""
token_url = ""
user_info_url = ""
scope = ""
