[package]
name = "ultimate-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[features]
prost = ["dep:prost-types"]

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hmac.workspace = true
ulid = { workspace = true, optional = true }
base64ct.workspace = true
base16ct.workspace = true
chrono.workspace = true
duration-str.workspace = true
rand.workspace = true
regex.workspace = true
prost-types = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }

[dev-dependencies]
dotenvy.workspace = true
