[package]
name = "fusion-iam"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "hetuiam"
path = "bin/hetuiam.rs"

[lints]
workspace = true

[features]

[dependencies]
# -- fusions
fusion-corelib = { workspace = true }
fusion-common = { workspace = true, features = ["with-uuid"]  }
fusion-core = { workspace = true, features = ["with-uuid"] }

# -- misc
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
derive_more = { workspace = true }
derive-getters = { workspace = true }
typed-builder = { workspace = true }
enum-iterator = { workspace = true }
o2o = { workspace = true }
uuid = { workspace = true }
log = { workspace = true }

# -- tokio & async
tokio = { workspace = true }
futures = { workspace = true }
async-stream = { workspace = true }

# -- tracing
fastrace = { workspace = true }

# -- db
fusion-db = { workspace = true, features = ["with-postgres", "with-uuid"] }
modelsql = { workspace = true, features = ["with-postgres", "with-uuid"] }
sqlx = { workspace = true }
sea-query = { workspace = true }
sea-query-binder = { workspace = true }

# -- qrcode
qrcode-rs = { workspace = true }
image = { workspace = true }

[dev-dependencies]
pretty_assertions.workspace = true
hyper = { workspace = true }
hyper-util = { workspace = true }
tower = { workspace = true }
fusion-core-macros = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
