[package]
name = "fusion-flow-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]

[lints]
workspace = true
