[fusion.log]
enable = true
with_target = true
with_file = true
with_thread_ids = false
with_thread_names = true
with_line_number = true
with_span_events = []
time_format = "%Y-%m-%d %H:%M:%S%.3f"
log_level = "info"
log_writer = "both"
log_dir = "./runs/logs/agent/"
log_name = "hetuflow-agent"
log_targets = [
    "tower_http=debug",
    "fusion_common=debug",
    "fusion_grpc=debug",
    "fusion_db=debug",
    "fusion=debug",
    "fusion_iam=debug",
    "hetuflow_core=debug",
    "hetuflow_agent=debug",
    "hetuflow_server=debug",
]

[fusion.log.otel]
enable = false
traces_sample = "always_on"
exporter_otlp_endpoint = "http://localhost:4317"

[fusion.app]
name = "hetuflow-agent"
time_offset = "+08:00"
run_mode = "dev"

[hetuflow.agent]
agent_id = "1dcb5bdf-8396-4218-9241-2e4928318624"
labels = { os = "linux", arch = "x86_64", gpu = "enabled" }

[hetuflow.agent.metadata]
region = "cn-hangzhou"
owner = "data-team"

[hetuflow.agent.polling]
max_concurrent_tasks = 20
enable_adaptive_polling = true
interval_seconds = 60
capacity_weight = 50
load_factor_threshold = 1

[hetuflow.agent.process]
enable_resource_monitoring = true
resource_monitor_interval = "30s"
cleanup_interval = "1h"
max_concurrent_processes = 8
process_timeout = "2h"
zombie_check_interval = "1h"

[hetuflow.agent.process.limits]
max_cpu_percent = 0.7
max_memory_bytes = 4194304

[hetuflow.agent.connection]
connect_timeout = "30s"
heartbeat_interval = "30s"
max_reconnect_attempts = 10
reconnect_interval = "10s"
# ip:port or domain:port
server_address = "127.0.0.1:9500"
