[fusion.log]
enable = true
with_target = true
with_file = true
with_thread_ids = false
with_thread_names = true
with_line_number = true
with_span_events = []
time_format = "%Y-%m-%d %H:%M:%S%.3f"
log_level = "info"
log_writer = "both"
log_dir = "./runs/logs/agent/"
log_name = "hetuflow-agent"
log_targets = ["hetuflow_core=debug", "hetuflow_agent=info"]

[fusion.log.otel]
enable = false
traces_sample = "always_on"
exporter_otlp_endpoint = "http://localhost:4317"

[fusion.app]
name = "hetuflow-agent"
time_offset = "+08:00"
run_mode = "dev"

[hetuflow.agent]
agent_id = "agent001"
labels = { gpu = "enabled" }
jwe_token = "eyJhbGciOiJFQ0RILUVTIiwiZW5jIjoiQTI1NkdDTSIsInR5cCI6IkpXRSIsImVwayI6eyJrdHkiOiJFQyIsImNydiI6IlAtMjU2IiwieCI6Iks5RmpXcThla0Fyd3ZONUZWQTRxQXhrT0lsckt3bXNucnR3bl91UWVhUzAiLCJ5Ijoia2tmOHh6OE5OQVBkVWVVZ3dZd2dFLWduTm5yQ3pMbmJtaDNGOG03M0pYZyJ9fQ..Ir8Nxg7fFvcLpnr0.zNa171oI5QksuAXN-gOiL9bHxERINR8y4qvxMRBoTc-vqy2blm_0CeEIuSlORYh5KXc32S5WtL4JwbTOKquhcIJQaxE1B5Oa4LPvkhTX1jxHRmv0mw1hCMx4EslQLd2UR47TslSjmyP7AtlLbtryt6wYVFmepsd-tu6i8shh2i9ECAezH_ljYcjfMSMVBwsQxdoJVDFbOaooVBOatqpoweqlMenVtU2nXO7XybwGjdt6P2pEEChhtSttZ6ZiQp0_BN74bEY-3YgvoMF7p78mQ7bk-J2J09Z84oSHrIYsxEdM9vzDVOVaJ8zTGOenow.G7TdY9nuY0WhBN8rTtPIpw"

[hetuflow.agent.metadata]
region = "cn-chongqing"

[hetuflow.agent.polling]
interval = "30"

[hetuflow.agent.process]
# 进程运行基础目录，默认为用户主目录下的 $HOME/.hetu/agent/runs
# run_base_dir =
enable_resource_monitoring = true
resource_monitor_interval = "30s"
max_concurrent_processes = 8
cleanup_interval = "1m"
process_timeout = "2h"
zombie_check_interval = "30m"

[hetuflow.agent.process.limits]
max_cpu_percent = 0.7
max_memory_bytes = 4194304

[hetuflow.agent.connection]
connect_timeout = "30s"
heartbeat_interval = "30s"
max_reconnect_attempts = 10
reconnect_interval = "10s"
# ip:port or domain:port
server_address = "127.0.0.1:9500"
