[ultimate.app]
run_mode = "DEV"
name = "ultimate"

[ultimate.security.pwd]
expires_in = 604800
default_pwd = "2024.Ultimate"

[ultimate.web]
enable = true
server_addr = "0.0.0.0:8888"

[ultimate.log]
enable = true
log_writer = "both"

# [ultimate.log.otel]
# exporter_otlp_endpoint = "http://localhost:4317"
# traces_sample = "always_on"

[ultimate.grpc]
enable = true
server_addr = "0.0.0.0:8889"
plaintext = true

[ultimate.db]
enable = true
host = "localhost"
port = 45432
database = "ultimate"
username = "ultimate"
password = "2024.Ultimate"
