[fusion.app]
run_mode = "DEV"
name = "fusion-iam"

[fusion.security.pwd]
expires_in = 604800
default_pwd = "2025.Fusiondata"

[fusion.web]
enable = true
server_addr = "0.0.0.0:58000"

[fusion.log]
enable = true
log_writers = ["stdout", "file"]
with_span_events = []
log_targets = [
  "fusion_db=debug",
  "fusion_common=debug",
  "fusion_web=debug",
  "jieyuan=debug",
]

[fusion.log.otel]
# enable = true
exporter_otlp_endpoint = "http://localhost:4317"
traces_sample = "always_on"

[fusion.db]
enable = true
url = "postgres://fusiondata:2025.Fusiondata@localhost:5432/fusiondata"
