/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TinyAlert: typeof import('@opentiny/vue-alert')['default']
    TinyAside: typeof import('@opentiny/vue-aside')['default']
    TinyButton: typeof import('@opentiny/vue-button')['default']
    TinyHeader: typeof import('@opentiny/vue-header')['default']
    TinyInput: typeof import('@opentiny/vue-input')['default']
    TinyLayout: typeof import('@opentiny/vue-layout')['default']
    TinyMain: typeof import('@opentiny/vue-main')['default']
    TinyMenu: typeof import('@opentiny/vue-menu')['default']
    TinyUserHead: typeof import('@opentiny/vue-user-head')['default']
  }
}
