[package]
name = "fusion-ai"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
publish = true

[lints]
workspace = true

[dependencies]
tokio = { workspace = true }
rig-core = { workspace = true }
rmcp = { workspace = true }
