[fusion.app]
run_mode = "DEV"
name = "fusion"

[fusion.security.pwd]
expires_in = 604800
default_pwd = "2024.Fusion"

[fusion.web]
enable = true
server_addr = "0.0.0.0:8888"

[fusion.log]
enable = true
log_writers = ["stdout", "file"]

# [fusion.log.otel]
# exporter_otlp_endpoint = "http://localhost:4317"
# traces_sample = "always_on"

[fusion.grpc]
enable = true
server_addr = "0.0.0.0:8889"
plaintext = true

[fusion.db]
enable = true
url = "postgres://fusiondata:2025.Fusiondata@localhost:5432/fusiondata"
