[package]
name = "ultimate-db-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true

[features]
with-rusqlite = ["rusqlite", "dep:sea-query-rusqlite"]

[dependencies]
quote = { workspace = true }
syn = { workspace = true }
proc-macro2 = { workspace = true }
sea-query = { workspace = true }
rusqlite = { workspace = true, optional = true }
sea-query-rusqlite = { workspace = true, optional = true }
chrono = { workspace = true }
uuid = { workspace = true }
