[package]
name = "fusion-scheduler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
publish = false
# default-run = "fusion-scheduler"

[lints]
workspace = true

[[bin]]
name = "fusion-scheduler"
path = "src/bin/fusion-scheduler.rs"

[dependencies]
# -- ultimates
ultimate-common = { workspace = true }
ultimate = { workspace = true }
ultimate-api = { workspace = true }

# -- db
ultimate-db = { workspace = true, features = ["uuid", "tonic"] }
sqlx = { workspace = true }
sea-query = { workspace = true }
modql = { workspace = true }

# -- grpc
ultimate-grpc = { workspace = true, features = ["uuid"] }
prost = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true, optional = true }

# -- fusions
fusion-server = { workspace = true }
fusion-scheduler-api = { workspace = true }
hierarchical_hash_wheel_timer = { workspace = true }

# -- misc
duration-str = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
uuid = { workspace = true }
croner = { workspace = true }

# -- async
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-cron-scheduler = { workspace = true }

# -- tracing
tracing = { workspace = true }


[build-dependencies]
tonic-build = { workspace = true }
