[ultimate.app]
run_mode = "DEV"
name = "fusion-scheduler"

[ultimate.security.pwd]
expires_in = 604800
default_pwd = "2024.Fusiondata"

[ultimate.web]
enable = true
server_addr = "0.0.0.0:58040"

[ultimate.grpc]
enable = true
server_addr = "0.0.0.0:58050"
plaintext = true

[ultimate.db]
enable = true
host = "localhost"
port = 45432
database = "fusiondata"
username = "fusiondata"
password = "2024.Fusiondata"
schema_search_path = "sched"

[ultimate.log]
log_targets = [
  "fusion_scheduler=debug",
  "fusiondata=debug",
  "fusiondata_context=debug",
  "ultimate_grpc=debug",
  "ultimate_db=debug",
  "ultimate=debug",
  "ultimate_common=debug",
  "tower_http=debug",
]

[fusion.scheduler]
node_id = "n01"
heartbeat_interval = "10s"
alive_timeout = "30s"
