[package]
name = "ultimate-db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
with-postgres = ["modelsql/with-postgres"]
with-sqlite = ["modelsql/with-sqlite"]
with-uuid = ["dep:uuid", "modelsql/with-uuid", "ultimate-api/uuid"]

[dependencies]
ultimate-common.workspace = true
ultimate-core = { workspace = true, features = ["modelsql", "ultimate-api"] }
ultimate-api = { workspace = true, features = ["modelsql"], optional = true }
modelsql = { workspace = true }
serde.workspace = true
serde_json.workspace = true
log.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid = { workspace = true, optional = true }
config = { workspace = true }
sqlx.workspace = true
sea-query.workspace = true
sea-query-binder.workspace = true
tonic = { workspace = true, optional = true }

[dev-dependencies]
anyhow.workspace = true
tracing-subscriber.workspace = true
