[package]
name = "ultimate-db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
# utoipa = ["dep:utoipa", "ultimate-api/utoipa"]
with-rusqlite = [
  "rusqlite",
  "dep:sea-query-rusqlite",
  "ultimate-db-macros/with-rusqlite",
]
with-ilike = []

[dependencies]
ultimate-common.workspace = true
ultimate.workspace = true
ultimate-api = { workspace = true }
ultimate-db-macros = { workspace = true }
async-trait.workspace = true
derive_more.workspace = true
serde.workspace = true
serde_with.workspace = true
serde_json.workspace = true
log.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid = { workspace = true }
config = { workspace = true }
sqlx.workspace = true
sea-query.workspace = true
sea-query-binder.workspace = true
sea-query-rusqlite = { workspace = true, optional = true }
chrono = { workspace = true }
rusqlite = { workspace = true, optional = true }
# utoipa = { workspace = true, optional = true }
tonic = { workspace = true, optional = true }

[dev-dependencies]
anyhow.workspace = true
tracing-subscriber.workspace = true
